tags = {
    "SOURCE_REQUEST":["<SOURCE_REQUEST>","</SOURCE_REQUEST>"],
    "NEXTSTEPS_REQUEST":["<NEXTSTEPS_REQUEST>","</NEXTSTEPS_REQUEST>"],
    "MOREDETAIL_REQUEST":["<MOREDETAIL_REQUEST>","</MOREDETAIL_REQUEST>"],
    "OG_QUERY":["<OG_QUERY>","</OG_QUERY>"],
    "SECURITY_CHECK":["<SECURITY_CHECK>","</SECURITY_CHECK>"],
}
allow_list = list(tags.keys())